### ISSUE TITLE
test_code生成不了图片

### ISSUE THREAD

**Issue by t1mkeeper** [SystemErrorWang/White-box-Cartoonization#1]
您好，我关注这个仓库有好几天了，我发现test_code里面生成不了预期的图片，控制台输入正常，输出的图片像素值全部为空（Nan），我检查了代码发现你没有用.mete加载图的方式，而是给generator变量赋值的方式，理论上是可以的，但我还是失败了，希望您有空可以下载仓库的代码跑一下试试，也许没问题，到时候我再仔细检查一遍我这里的代码

**Comment by SystemErrorWang** [comment]
I tested the inference code in this repository, it works normally in my laptop.
my environment is Windows 10, nvidia gtx1070 maxq, cuda 9.0, python 3.6.8 and tensorflow-gpu 1.12.0

**Comment by t1mkeeper** [comment]
一个很小的问题 o_o，还是提一下吧
[guided_filter.py#L10](https://github.com/SystemErrorWang/White-box-Cartoonization/blob/ae9bc91e51454ad6e8e3d0ab3ca8c7190e21c61c/test_code/guided_filter.py#L10)
https://github.com/SystemErrorWang/White-box-Cartoonization/blob/ae9bc91e51454ad6e8e3d0ab3ca8c7190e21c61c/test_code/guided_filter.py#L10
Python2里面应该是1.0/(k_size**2)，否则weight得不到想要的浮点数，所以我的结果都是Nan
