### ISSUE TITLE
Should the random weights in color_shift be `tf`, instead of `np`?

### ISSUE THREAD

**Issue by GatzZ** [SystemErrorWang/White-box-Cartoonization#10]
https://github.com/SystemErrorWang/White-box-Cartoonization/blob/aed441cc886f783b180a9ac076b59ecee77e953e/train_code/utils.py#L22-L35

If we use `np.random.uniform` to generate b, g, r's weight, then they would be constant values, which will not change during training. That should not be our original purpose of the paper.

Is that correct? Thanks.

**Comment by SystemErrorWang** [comment]
I guess you are right, the weight of b, g, r should be randomized during training.

**Comment by GatzZ** [comment]
> I guess you are right, the weight of b, g, r should be randomized during training.

thanks，this is helpful
