### ISSUE TITLE
'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by HECKNYANG** [SystemErrorWang/White-box-Cartoonization#107]
Wang, 我有个问题.
在练习火车的过程中 发现了这样的错误
以上错误是由于数据集的规格不固定而产生的错误吗？？？？

**Comment by SystemErrorWang** [comment]
@HECKNYANG 
It's ok to use English. The google translation always makes mistakes.
I guess you came across this problem during training, this should be because the dataloader failed to load the training data

**Comment by HECKNYANG** [comment]
Thank you. I'm facing a new error
TypeError: only size-1 arrays can be converted to python scalars. Is this a version problem?
