### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by YHJ2c95** [SystemErrorWang/White-box-Cartoonization#11]
### 巡礼
[一个巡礼网站 少量 map real life anime locations](https://www.iakesi.net/)

专门做完layout（基本语义布局）后的[bili video](https://www.bilibili.com/video/av94309755)
cutmix [幸运星巡礼](https://zhuanlan.zhihu.com/p/158097617)

[bili 动态 例](https://h.bilibili.com/49399777)
[bili 动态 例](https://h.bilibili.com/49108595)

这些巡礼的图片对应动漫scene,Semantic对不上啊
然后有个**Semantic Correspondence**任务，感觉能用

### 二三次元对比，动漫x现实

[风格化，调色后期](https://www.bilibili.com/video/BV1gb411K78p)

摄影合成/图像融合 二次元与现实融合（Image Harmonization）
@msinsanity [link](https://vk.com/msinsanity)

@[bilibili-go海盗](https://h.bilibili.com/18259362)
并且提供的白背景的分割素材（动态id：22632857，看评论）

### 动漫梗图，少样本标注 作风格增广
anime related style / content parody collection
例如danbooru里的【parody，meme，alternate】使用的特殊tag

梗推荐：
Sailor Moon Redraw | #sailormoonredraw
#STAYHOMEwithTRIGGER
Tokyo snowfalls Japanese TV interviewed a couple | #Special Feeling/Special Mood 特別な気分
shiba inu&fox | #Right-Hook Dog 右フック犬
drink resting on breasts | #tapioca Challenge #タピオカチャレンジ
未来日記 由乃 Yandere Pose | Yuno Face #Yandere Trance
新房45° シャフト角度 | #Shaft Head Tilt

### gal白给的大量数据集
差分，设定背景等等
不用白不用（可能有严重的 版权问题）

**Comment by SystemErrorWang** [comment]
thank you for telling me this, it may help a lot. In fact I tried to find similar resources but failed

**Comment by lllyasviel** [comment]
？？？？这么强的吗

**Comment by huaji0353** [comment]
还推荐用用动漫梗图（parody，meme）做数据增广

**Comment by huaji0353** [comment]
### 截图收集网站
[AnimeShot2](https://as2.bitinn.net/)
[animeloop](https://animeloop.org/)
[gifmagazine anime](https://gifmagazine.net/gifs/search_results?locale=en&search[word]=アニメ)
[sakugabooru](https://sakugabooru.com/)
各种动画的截图/片段都有，风格化要的就是这种数据集吧
