### ISSUE TITLE
Getting nan discriminator and generator loss

### ISSUE THREAD

**Issue by Nerdyvedi** [SystemErrorWang/White-box-Cartoonization#13]
Hi, 
Thank you for uploading such a great work.

I am training the model with my custom dataset, only for portraits. 
I followed the steps mentioned, the pretrain.py runs properly and saves the model. But, on running train.py I am getting both discriminator and generator losses as NaN. The reconstruction loss does have some value, not sure why I am getting this. 

Your help would mean a lot.

One more question. What should be the size of the dataset in order to get decent results. For instance, Paper mentioned use of 10000 cartoon faces, Is it possible to get great results with a smaller dataset?

**Comment by Nerdyvedi** [comment]
Okay. So turns out , the error was due to not enough GPU memory available.
@SystemErrorWang , Would be grateful if you could help me with my second question. What should be the size of portraits cartoon dataset to get desirable results ?

**Comment by SystemErrorWang** [comment]
@Nerdyvedi In fact I did not try to train the network with a smaller dataset so I may not be very clear with it. But CartoonGAN and AnimeGAN all trained their models with datasets which contain about 3000-4000 images. Thus I think 3000 should be ok. BTW, art2real train their models with even smaller dataset.

**Comment by Nerdyvedi** [comment]
Okay. I just have 150 :( . Model does not perform well on it.
