### ISSUE TITLE
how to use it using AMD RX 570?

### ISSUE THREAD

**Issue by jeraldpunx** [SystemErrorWang/White-box-Cartoonization#15]
how to use it using AMD RX 570?

**Comment by SystemErrorWang** [comment]
@jeraldpunx sorry i didn't try it on AMD's gpu, maybe you need to confirm whether it supports cuda, cudnn and tensorflow-gpu

**Comment by benjamintli** [comment]
You might be able to use AMD's rocm version of tensorflow

**Comment by jeraldpunx** [comment]
sorry, any guide on how to use it?
