### ISSUE TITLE
anime2anime is possible?

### ISSUE THREAD

**Issue by YHJ2c95** [SystemErrorWang/White-box-Cartoonization#17]
#### 这里说的影响，就是画面，色彩&后期效果。内容是：作画；画风，原画，线条人设这些。

举例：（摄影故意拉高光，唐突色彩设计审美，低成本动画，...）
> 恋爱小行星的色彩，白日，夜晚场景
> 请问你要来点兔子吗？，头发边缘高光（光圈 halo）

**Sooo?, Not**
#### what kind method make it real?
> 不同于，此repo的现实滤镜，动画里的内容是很相近的，即使不引入注意力机制、空域标准化 等....手段
> 估计也能搞出能看的效果（[推荐阅读，使用patch based discriminator ](https://github.com/SystemErrorWang/White-box-Cartoonization/issues/17#issuecomment-653328767)）

transfer between two anime series
实现出来（我吹爆！），要是搞出业界都能满足的那甚好！（救救业界⑧，审美都要奇怪了...）
把京阿尼画风给迁移到新海诚那上面？
又或者把PA迁到京阿尼上面（想看PA版K-ON! 2333）？

### **mmd2anime** : 卡通渲染相关，将mmd粗模，等3DCG渲染成特定动画风格
用于训练分镜，演出的设计，漫画分镜设计（等我补一个支持3D人偶的分镜软件）
> 灵感来源于[动画制作中的layout](https://i0.hdslb.com/bfs/album/705100470465c322de3bc91b157ad58354102a9a.jpg)
> 既然这么难学习位置关系，那就3D直接风格化吧，保留的内容几乎是等同，并且可以用3Dlayout的骨架信息代替帧帧手工的关键点标注；与其折腾于2D手绘互转，3D预渲染的效果与成绩应该是非常可观的！

低成本实现 中高的动画品质，mmd2anime+anime2anime可能是方向

mmd[舞蹈](https://www.bilibili.com/video/av3903564)/[小剧场](https://www.bilibili.com/video/av38508) 
参考BanG Dream [第一季 2D动画](https://www.bilibili.com/bangumi/media/md5807)；[第二季 3DCG](https://www.bilibili.com/bangumi/media/md4762002),[第三季 3DCG](https://www.bilibili.com/bangumi/media/md28224078)

#### not noly that , is possible transfer these gega（原画） and sakuga（作画） style ?
对于内容，（作画）画风，原画，线条人设这些复杂边缘语义，嘛
作画风格迁移，是时空特征，动画自动中割研究资料也很少，很难（

再就是
### re-implement a anime version deepfakeface ?
动画换脸，例如下边这是个 亚丝娜<->御坂 的cyclegan。
[cyclegan-for-unsupervised-translation-in-anime](https://bellchen.me/research/cs/gan/cyclegan-for-unsupervised-translation-in-anime/)
[youtube - deepfakeanime](https://www.youtube.com/watch?v=uqqrXGWf5MQ)

二创，能网红。

### 附，版权问题：
生成模型严格定义上是侵犯版权的（嘛，你复制了，修改了人家的作品）
但公众方面，部分宽松，但边界未知？（就看人家告不告你，你国版权方搞不搞事；用有名的，或那旧番老番，那种倒闭了的动画公司估计稳）
> 日本改正著作権法「著作権法４７条の７」
> 進化する機械学習パラダイス ～改正著作権法が日本のAI開発をさらに加速する～
> 機械学習に使うデータセットの著作権について

**Comment by SystemErrorWang** [comment]
It's a good idea to try anime2anime, but as far as I know, this is far beyond the possibility of current white-box framework. (cyclegan based methods maybe suitble for anime2anime, but to avoid bad cases and improve controllability, segmentation and color transfer maybe more preactical for this task) 
I am also trying some improvements of this work, and will update my progress occasionally.

**Comment by huaji0353** [comment]
感谢回复！

我现在没有卡，去尝试你的模型
现在只是作为一个idea提出，相关实验还没有做过

考虑未来将不仅仅需要anime2anime这样的配对集
我就先优先制作动画配对数据集，尽管这也需要很多的工作
[dataset_system_plan.md](https://github.com/huaji0353/AnimeResearch/blob/master/dataset_system_plan.md)

**Comment by huaji0353** [comment]
currently related works (interesting SOTA)

（deep patchs based）
https://arxiv.org/abs/2007.00653
https://taesung.me/SwappingAutoencoder/
Swapping Autoencoder for Deep Image Manipulation

**Comment by SystemErrorWang** [comment]
@huaji0353 training dataset uploaded (see another dataset related issue)

**Comment by huaji0353** [comment]
> @huaji0353 training dataset uploaded (see another dataset related issue)

好的。
我大致看了一下 #5 
并[imggrid了一下其中的face](https://pan.baidu.com/s/1TRdvycTaN5v6j7RubRlWnw) code:2333
很明显，多样性很弱，不论是风格样式还是内容都 采样太少
以至于人像，就学成映射，某个角色（在场景下）对应的selfie2anime
而且风格与内容难以解耦，影响到风格化的泛化能力

关于实景也是这样严重的问题，数据集不够干净（random crop？）

> 所以得赶快整[一个这样的标注站](https://github.com/huaji0353/AnimeResearch/blob/master/dataset_system_plan.md)（（（

大概模型就学了很浅的一部分特征吧（（
（我估计Deep patch Image[朱俊彦大佬的那篇](https://twitter.com/junyanz89/status/1279943153110454274)，在你这数据集上跑就能得到，单纯学特征更好的结果）

**Comment by yushuinanrong** [comment]
@YHJ2c95 姐妹或者哥们，你是日本人吗？看你的文字好费劲。。。还是二次元就这种叙事风格？语文老师看到要气到爆炸。
