### ISSUE TITLE
Pretrained model download url requests

### ISSUE THREAD

**Issue by zomkey** [SystemErrorWang/White-box-Cartoonization#19]
Hi，thanks for your great work！
I wanted to use pretrained-model to run demo, but found the url (https://drive.google.com/open?id=1JfJzJbNjAWBIHGm9mc_R9dXv7DAw3tZc) is already not available. I want to ask  whethre you can release a new url for pretrained model.
Hope for your reply, thank you very much!

**Comment by SystemErrorWang** [comment]
@zomkey you can find it at test_code/saved_models

**Comment by SystemErrorWang** [comment]
@zomkey updated, pls see new url in readme.

**Comment by zomkey** [comment]
> @zomkey updated, pls see new url in readme.

ok, thank you!!
