### ISSUE TITLE
Noise in result images during training 

### ISSUE THREAD

**Issue by HoSyTuyen** [SystemErrorWang/White-box-Cartoonization#24]
Thank you for your awesome work.
I have trained your model with my own data (about 10k real face and 10k anime face), the result looks potential but there are a lot of abnormal pixels. The figure bellow shows a sample in iter 50k. 
Could you give me some advice about this problem? Thank you so much.
![image](https://user-images.githubusercontent.com/32817741/87442117-19a84c80-c61e-11ea-824e-35889563adda.png)

**Comment by SystemErrorWang** [comment]
@HoSyTuyen This is likely caused by pixel value overflow, you can try adding a tanh layer after the generator or other methods to constrain the output to be in (-1, 1) range

**Comment by HoSyTuyen** [comment]
> @HoSyTuyen This is likely caused by pixel value overflow, you can try adding a tanh layer after the generator or other methods to constrain the output to be in (-1, 1) range

Thank you so much, that's exactly pixel value overflow. I have checked code and realized that the output of G do not constrain to be in range [-1,1]. And I also find that the your function write_batch_image in utils.py (in train code) do not constrain image to be in range [0,255] for sample images. That makes the sample image looks like the picture above.

Once again, Thank you so much !!!
