### ISSUE TITLE
Separate pre-trained weights available for the UNET generator?

### ISSUE THREAD

**Issue by sayakpaul** [SystemErrorWang/White-box-Cartoonization#25]
Hi.

Thank you for this super impressive work. 

I was wondering if you have the separate pre-trained weights for the UNET-based generator network. If so, could you please help me find it?

**Comment by SystemErrorWang** [comment]
sorry, I didn't save the pre-trained model, but you can use pretrain.py in train_code folder

**Comment by sayakpaul** [comment]
No problem. I actually created different TensorFlow Lite models from the checkpoints you are already providing. The results are coming out quite well. Here's the Colab Notebook: https://colab.research.google.com/github/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/CartoonGAN_TFLite.ipynb. 

Do you mind if we publish the TensorFlow Lite models on TensorFlow Hub, of course with a due citation?
