### ISSUE TITLE
 No module named 'util'

### ISSUE THREAD

**Issue by ferretgeek** [SystemErrorWang/White-box-Cartoonization#27]
raceback (most recent call last):
  File "train.py", line 11, in <module>
    import utils
  File "E:\White-box-Cartoonization\train_code\utils.py", line 11, in <module>
    from selective_search.util import switch_color_space
  File "E:\White-box-Cartoonization\train_code\selective_search\__init__.py", line 1, in <module>
    from .core import selective_search, box_filter
  File "E:\White-box-Cartoonization\train_code\selective_search\core.py", line 3, in <module>
    from util import oversegmentation, switch_color_space, load_strategy
ModuleNotFoundError: No module named 'util'

Windows10 2004，i7-9750H+1660TI
python3.6.8
TensorFlow1.12.0/1.13.0均报此错误
但是可以正常使用预训练模型进行推理

**Comment by SystemErrorWang** [comment]
I think comment line11 and line12 in utils.py can help

**Comment by ferretgeek** [comment]
> 我认为评论行 11 和行 12 utils.py可以帮助

抱歉我的水平不足，不太懂得该如何修改

**Comment by SystemErrorWang** [comment]
@ferretgeek  Just comment this two lines

**Comment by kimusu2008** [comment]
from selective_search.util import oversegmentation, switch_color_space, load_strategy
from selective_search.structure import HierarchicalGrouping
