### ISSUE TITLE
replacing slim layers with tf layers

### ISSUE THREAD

**Issue by kezakool** [SystemErrorWang/White-box-Cartoonization#36]
Hi,

Thank you for all your work this is great! no bug here, but i was asking myself why you choose tf_slim instead of tf for convolutions layers?

thx

**Comment by SystemErrorWang** [comment]
@kezakool this is just a personal preference, I think tf.contrib.slim is easier to use than other tensorflow API
btw, I transfer to pytorch now because tensorflow APIs are too complicated.
