### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by zhangyunming** [SystemErrorWang/White-box-Cartoonization#4]
hi ，关注这个项目几天了，挺棒。做了一些测试，我比较关注人的卡通化，在我测试过程中，我发现人脸卡通化后，容易出现很多纹路，看起来感觉变老了。如果我通过重新训练来改善人脸，在数据准备等方面有哪些思路呢，谢谢。

**Comment by SystemErrorWang** [comment]
Train the model purely on face datasets may improve the performace on facial data, or you can try my previous work, which was trained on human face dataset: https://github.com/SystemErrorWang/CartoonGAN

If you would like to improve the model itself, more conditions like face keypoints and segmentation map may help (but i have not tried these methods yet).

**Comment by zhiguangyang** [comment]
I have trained the model purely on face datasets based on the pre-train model given by author, but it not work, the results are even worse than the pre-train model.

**Comment by itomorrower08** [comment]
@zhangyunming I have tried to train the model purely on face datasets based on the pre-train model given by author also,  and the result also worse than the pre-train model. Three are some small green block in the results and when use the guide-fliter to deal with the result, the green block disappear but some black points appear, Did you meet this problem?

**Comment by zhaowt61** [comment]
@SystemErrorWang 为什么pretrained model的结果没有皱纹呢？望指教，谢谢！

**Comment by SystemErrorWang** [comment]
@zhaowt61 pretrain model是为了忠实还原输入，输入是啥输出就是啥

**Comment by zhaowt61** [comment]
@SystemErrorWang 请问能留一下邮箱吗？在复现的时候遇到了一些问题，用了您提供的数据集和默认settings，但是复现出来的结果和pretrained model有些差异。感谢！

**Comment by SystemErrorWang** [comment]
@zhaowt61 你说的pretrained model是我在这个repo放出来的那个吗？这个模型在人脸数据集上面也不能保证百分百没有artifacts。如果你想要人脸的模型，可以看我改进的那个repo，有pytorch的人脸卡通画模型

**Comment by zhaowt61** [comment]
@SystemErrorWang 我用这个repo去做training，train出来的效果没有这个repo里给出来的pretrained model的效果好，我看这个repo里给的pretrained model效果非常理想啊
