### ISSUE TITLE
GPU memory question？

### ISSUE THREAD

**Issue by bityigoss** [SystemErrorWang/White-box-Cartoonization#48]
How much GPU memory does this model occupy in inference stage ? 
On my v100-GPU, it takes about 7GB of GPU memory, is this normal ? Do you have any suggestions on reducing GPU memory usage?

**Comment by SystemErrorWang** [comment]
@bityigoss it depends on the resolution of your input image. As far as I know, 8 gb gpu memory is enough to train the model with batch size 16 and resolution 256.
