### ISSUE TITLE
G(I_p)貌似都被替换成了F_dgf(G(I_p))?

### ISSUE THREAD

**Issue by zhen8838** [SystemErrorWang/White-box-Cartoonization#52]
作者你好，按照论文里面的描述的结构损失和纹理损失中，输入的生成图像应该是没有进行guided filter的，但是[train.py](
https://github.com/SystemErrorWang/White-box-Cartoonization/blob/50b115e5adfefa12e0aad7b128a9e7cce7a9f2c5/train_code/train.py#L50)中，生成器生成的图像都被替换成了滤波后的图像，这样后面只要用到G(I_p)的地方都被改成了F_dgf(G(I_p))，这是本来所期望的吗？
```python
    output = network.unet_generator(input_photo)
    output = guided_filter(input_photo, output, r=1)
```

**Comment by zhen8838** [comment]
谢谢作者，这里我理解了。我想再次请教一下从头开始在新的数据集训练一段之间后发现生成的图像过于真实，我想尝试加大g_loss_blur和superpixel_loss的权重，这样做合理吗？

**Comment by SystemErrorWang** [comment]
@zhen8838 直接减小content loss权重的试一试？

**Comment by zhen8838** [comment]
好的，我多尝试下。
