### ISSUE TITLE
when the face is with small pixels,the face is generated without any detail information.

### ISSUE THREAD

**Issue by Dongshengjiang** [SystemErrorWang/White-box-Cartoonization#53]
when I test your model with a large image contain many people, whose face only accupy a little pixels. the genertated face would not genrate any detail information, such as nose, ears, mouth. Is this the shortcoming of your method?

**Comment by SystemErrorWang** [comment]
@Dongshengjiang  To cartoonize a video, you need to split the video into frames, process each frame and then concatenate processed frames back to a video.

**Comment by SystemErrorWang** [comment]
@Dongshengjiang This model is trained on unpaired data and only focus on low-level feature cartoonization. If you want to cartoonize face images, 256*256 is the best resolution, or the resolution should be at least neat to 256*256. As cartoonzation will generate a smoothed effect, details may be lost  when the resolution is too small.

**Comment by Dongshengjiang** [comment]
thanks for your answer!  I see.
