### ISSUE TITLE
In bilibili's demo video, it doesn't seem to perform well at night?

### ISSUE THREAD

**Issue by TCBocean** [SystemErrorWang/White-box-Cartoonization#9]
In bilibili's demo video, it doesn't seem to perform well at night? Is it because the training data rarely involve night scenes?
I see that the comparison results given in the thesis are relatively bright pictures and the pictures all have a certain composition, without involving the night scene.

**Comment by SystemErrorWang** [comment]
Yes, when training the network, we did not consider too much for the night scenes, and the datasets are not designed for these use cases. If trained on selected night images, I think the performance on nights will be increased.

**Comment by TCBocean** [comment]
Similar to my guess, but this is still a good job.
